### ISSUE TITLE
Getting the custom 404 page to work

### ISSUE THREAD

**Issue by taylorl-ee** [professorsugoi/Deploy-Astro-Neocities#2]
Might not be the best place to ask, but the custom 404 page does not work when I either create a 404.astro or not_found.html -- do you know why this might be?

Thanks for this wonderful tool!

**Comment by taylorl-ee** [comment]
Turns out it can be done by creating a not_found.html file in the /public/ directory!

**Comment by professorsugoi** [comment]
ill remember this tip if i have the same issue arise- thanks!
